# Generated by Django 3.2.23 on 2023-12-07 18:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
